// ============================================
// Arabic UI Dictionary & Constants
// ============================================

export const AR = {
  // App
  appName: 'فودافون كاش',
  appTagline: 'نظام إدارة المحافظ والعملاء',

  // Navigation
  nav: {
    dashboard: 'لوحة التحكم',
    wallets: 'المحافظ',
    clients: 'العملاء',
    transactions: 'المعاملات',
    payments: 'المدفوعات',
    reports: 'التقارير',
    settings: 'الإعدادات',
  },

  // Common Actions
  actions: {
    add: 'إضافة',
    edit: 'تعديل',
    delete: 'حذف',
    save: 'حفظ',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    close: 'إغلاق',
    search: 'بحث',
    filter: 'تصفية',
    export: 'تصدير',
    print: 'طباعة',
    download: 'تحميل',
    upload: 'رفع',
    refresh: 'تحديث',
    back: 'رجوع',
    next: 'التالي',
    previous: 'السابق',
    viewAll: 'عرض الكل',
    viewDetails: 'عرض التفاصيل',
    addNew: 'إضافة جديد',
  },

  // Wallets
  wallets: {
    title: 'المحافظ',
    wallet: 'محفظة',
    addWallet: 'إضافة محفظة',
    editWallet: 'تعديل المحفظة',
    walletName: 'اسم المحفظة',
    phoneNumber: 'رقم الهاتف',
    initialBalance: 'الرصيد الابتدائي',
    currentBalance: 'الرصيد الحالي',
    isActive: 'نشطة',
    notes: 'ملاحظات',
    totalBalance: 'إجمالي الأرصدة',
    noWallets: 'لا توجد محافظ',
  },

  // Clients
  clients: {
    title: 'العملاء',
    client: 'عميل',
    addClient: 'إضافة عميل',
    editClient: 'تعديل العميل',
    clientName: 'اسم العميل',
    nationalId: 'الرقم القومي',
    address: 'العنوان',
    phones: 'أرقام الهاتف',
    addPhone: 'إضافة رقم',
    primaryPhone: 'الرقم الرئيسي',
    phoneLabel: 'وصف الرقم',
    totalDebt: 'إجمالي الدين',
    isActive: 'نشط',
    noClients: 'لا يوجد عملاء',
    statement: 'كشف حساب',
    downloadStatement: 'تحميل كشف حساب PDF',
    phoneLabelOptions: {
      personal: 'شخصي',
      work: 'عمل',
      other: 'آخر',
    },
  },

  // Transactions
  transactions: {
    title: 'المعاملات',
    transaction: 'معاملة',
    addTransaction: 'إضافة معاملة',
    transactionType: 'نوع المعاملة',
    vcAmount: 'مبلغ فودافون كاش',
    cashAmount: 'المبلغ النقدي',
    feeAmount: 'العمولة',
    paymentStatus: 'حالة السداد',
    amountPaid: 'المبلغ المدفوع',
    amountDue: 'المبلغ المتبقي',
    recipientPhone: 'رقم المستلم',
    description: 'الوصف',
    transactionDate: 'تاريخ المعاملة',
    proof: 'إثبات التحويل',
    uploadProof: 'رفع صورة الإثبات',
    noTransactions: 'لا توجد معاملات',
    types: {
      TRANSFER_OUT: 'تحويل صادر',
      TRANSFER_IN: 'تحويل وارد',
      DEPOSIT: 'إيداع',
      WITHDRAW: 'سحب',
    },
    typeDescriptions: {
      TRANSFER_OUT: 'تحويل فودافون كاش للعميل مقابل نقدي',
      TRANSFER_IN: 'استلام فودافون كاش من العميل مقابل نقدي',
      DEPOSIT: 'إيداع رصيد في المحفظة',
      WITHDRAW: 'سحب رصيد من المحفظة',
    },
    status: {
      paid: 'مدفوع',
      partial: 'مدفوع جزئياً',
      debt: 'دين',
    },
  },

  // Payments
  payments: {
    title: 'المدفوعات',
    payment: 'دفعة',
    addPayment: 'تسجيل دفعة',
    amount: 'المبلغ',
    paymentMethod: 'طريقة الدفع',
    paymentDate: 'تاريخ الدفع',
    notes: 'ملاحظات',
    noPayments: 'لا توجد مدفوعات',
    allocatedTo: 'مخصصة لمعاملة',
    fifoNote: 'سيتم توزيع الدفعة تلقائياً على أقدم الديون أولاً (FIFO)',
    methods: {
      cash: 'نقدي',
      vc_transfer: 'تحويل فودافون كاش',
      bank: 'تحويل بنكي',
    },
  },

  // Reports & Dashboard
  reports: {
    title: 'التقارير',
    dashboard: 'لوحة التحكم',
    profitReport: 'تقرير الأرباح',
    debtReport: 'تقرير الديون',
    clientReport: 'تقرير العملاء',
    dateRange: 'الفترة',
    from: 'من',
    to: 'إلى',
    today: 'اليوم',
    thisWeek: 'هذا الأسبوع',
    thisMonth: 'هذا الشهر',
    lastMonth: 'الشهر الماضي',
    custom: 'مخصص',
  },

  // KPIs
  kpis: {
    todayProfit: 'ربح اليوم',
    weekProfit: 'ربح الأسبوع',
    monthProfit: 'ربح الشهر',
    totalBalance: 'إجمالي الأرصدة',
    totalDebts: 'إجمالي الديون',
    totalClients: 'إجمالي العملاء',
    activeClients: 'عملاء نشطين',
    todayVolume: 'حجم التداول اليوم',
    todayTransactions: 'معاملات اليوم',
    weekTransactions: 'معاملات الأسبوع',
    monthTransactions: 'معاملات الشهر',
  },

  // Debt Aging
  debtAging: {
    title: 'أعمار الديون',
    current: '0-7 أيام',
    week: '8-30 يوم',
    month: '31-60 يوم',
    overdue: 'أكثر من 60 يوم',
  },

  // Statement
  statement: {
    title: 'كشف حساب',
    clientStatement: 'كشف حساب العميل',
    openingBalance: 'الرصيد الافتتاحي',
    closingBalance: 'الرصيد الختامي',
    periodDebits: 'إجمالي المديونية',
    periodCredits: 'إجمالي المدفوعات',
    debit: 'مدين',
    credit: 'دائن',
    balance: 'الرصيد',
    carriedForward: 'رصيد مُرحّل',
    generatedOn: 'تم إصدار هذا الكشف بتاريخ',
    autoGenerated: 'هذا الكشف صادر آلياً ولا يحتاج إلى توقيع',
    clientSignature: 'توقيع العميل',
    shopStamp: 'ختم المحل',
  },

  // Dates
  dates: {
    today: 'اليوم',
    yesterday: 'أمس',
    days: 'أيام',
    weeks: 'أسابيع',
    months: 'شهور',
    createdAt: 'تاريخ الإنشاء',
    updatedAt: 'تاريخ التحديث',
  },

  // Validation
  validation: {
    required: 'هذا الحقل مطلوب',
    invalidPhone: 'رقم الهاتف غير صحيح (يجب أن يبدأ بـ 01)',
    invalidAmount: 'المبلغ يجب أن يكون رقماً موجباً',
    invalidDate: 'التاريخ غير صحيح',
    minLength: 'الحد الأدنى للأحرف هو',
    maxLength: 'الحد الأقصى للأحرف هو',
    selectWallet: 'يرجى اختيار محفظة',
    selectClient: 'يرجى اختيار عميل',
    selectType: 'يرجى اختيار نوع المعاملة',
    noDebts: 'لا توجد ديون مستحقة لهذا العميل',
    amountExceedsDebt: 'المبلغ أكبر من إجمالي الدين',
  },

  // Messages
  messages: {
    success: 'تمت العملية بنجاح',
    error: 'حدث خطأ',
    confirmDelete: 'هل أنت متأكد من الحذف؟',
    noData: 'لا توجد بيانات',
    loading: 'جاري التحميل...',
    saving: 'جاري الحفظ...',
    saved: 'تم الحفظ',
    deleted: 'تم الحذف',
    walletCreated: 'تم إنشاء المحفظة بنجاح',
    clientCreated: 'تم إنشاء العميل بنجاح',
    transactionCreated: 'تم إنشاء المعاملة بنجاح',
    paymentRecorded: 'تم تسجيل الدفعة بنجاح',
    proofUploaded: 'تم رفع صورة الإثبات بنجاح',
    pdfGenerated: 'تم إنشاء ملف PDF بنجاح',
    networkError: 'خطأ في الاتصال بالخادم',
    unknownError: 'حدث خطأ غير متوقع',
  },

  // Currency
  currency: {
    egp: 'ج.م',
    symbol: 'ج.م',
  },

  // Placeholders
  placeholders: {
    search: 'بحث...',
    selectWallet: 'اختر محفظة',
    selectClient: 'اختر عميل',
    selectType: 'اختر النوع',
    enterAmount: 'أدخل المبلغ',
    enterPhone: 'أدخل رقم الهاتف',
    enterName: 'أدخل الاسم',
    enterDescription: 'أدخل الوصف',
    enterNotes: 'أدخل ملاحظات (اختياري)',
  },
} as const;

// Transaction type colors
export const TRANSACTION_TYPE_COLORS: Record<string, string> = {
  TRANSFER_OUT: 'bg-blue-100 text-blue-800',
  TRANSFER_IN: 'bg-green-100 text-green-800',
  DEPOSIT: 'bg-purple-100 text-purple-800',
  WITHDRAW: 'bg-orange-100 text-orange-800',
};

// Payment status colors
export const PAYMENT_STATUS_COLORS: Record<string, string> = {
  paid: 'bg-green-100 text-green-800',
  partial: 'bg-yellow-100 text-yellow-800',
  debt: 'bg-red-100 text-red-800',
};

// Chart colors
export const CHART_COLORS = {
  primary: '#e60000',
  secondary: '#4a4d4e',
  success: '#10b981',
  warning: '#f59e0b',
  danger: '#ef4444',
  info: '#3b82f6',
  gradient: ['#e60000', '#ff4d4d', '#ff8080'],
};

// Date format options
export const DATE_FORMAT = 'yyyy-MM-dd';
export const DATETIME_FORMAT = 'yyyy-MM-dd HH:mm:ss';
export const DISPLAY_DATE_FORMAT = 'dd/MM/yyyy';
export const DISPLAY_DATETIME_FORMAT = 'dd/MM/yyyy HH:mm';

// Pagination
export const DEFAULT_PAGE_SIZE = 10;
export const PAGE_SIZE_OPTIONS = [10, 25, 50, 100];

// Phone regex (Egyptian)
export const EGYPTIAN_PHONE_REGEX = /^01[0125][0-9]{8}$/;

// File upload limits
export const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5MB
export const ALLOWED_FILE_TYPES = ['image/jpeg', 'image/png', 'image/gif', 'image/webp'];
